### ISSUE TITLE
`ocdev component set` should fail when the target component does not exist

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/ocdev#143] opened 2018-03-05 06:17 UTC
```console
$ ocdev component set randomcomp
Switched to component: randomcomp
```

blocked on #53

**Comment by kadel** [comment] 2018-04-04 13:12
this is no longer blocked

but it is duplicate of https://github.com/redhat-developer/ocdev/issues/127

**Closed by kadel** 2018-04-04 13:12 UTC

**Comment by kadel** [comment] 2018-04-05 08:35
Duplicate of #127
