### ISSUE TITLE
ocdev switches to non-existent components

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/ocdev#310] opened 2018-04-05 11:50 UTC
```console
$ ocdev list
You have deployed:
nodejs1 using the nodejs component
nodejs2 using the nodejs component
nodejs3 using the nodejs component
nodejs4 using the nodejs component

$ ocdev component set abcd
Switched to component: abcd

$ ocdev component abcde
Switched to component: abcde
```

**Comment by kadel** [comment] 2018-04-05 12:07
Duplicate of #127

**Comment by kadel** [comment] 2018-04-05 12:08
This is just another formulation of an already existing issue.

**Closed by kadel** 2018-04-05 12:08 UTC
Labels: kind/bug, priority/high
